# Benchmarks

## Surprise on Data

In [28]:
from surprise import Dataset, Reader, SVD
from surprise.model_selection import cross_validate
import pandas as pd

In [29]:
df = pd.read_csv('data/cleaned.csv')
df.head()

    app_id  is_recommended  user_id
0   534380               1    10531
1    42700               0   185293
2   602960               1   319249
3   976730               0   747545
4  1091500               1  2113544

In [30]:
reader = Reader(line_format='item rating user', sep=',', skip_lines=1, rating_scale=(0, 1))
data = Dataset.load_from_file('data/cleaned.csv', reader=reader)
full_train = data.build_full_trainset()

In [ ]:
svd = SVD()
results = cross_validate(svd, data, measures=['RMSE'], cv=5, verbose=True)

In [31]:
svd_fit = svd.fit(full_train)

In [44]:
svd_fit.bi

array([-0.07391577,  0.02504232,  0.08813493, ...,  0.07392884,
       -0.41369429,  0.04063683])

In [ ]:
user = 6
user = full_train.to_raw_uid(user)
top = []
for item in full_train.all_items():
    item = full_train.to_raw_iid(item)
    prediction = svd_fit.predict(user, item)
    uid, iid, true, pred = prediction[0], prediction[1], prediction[2], prediction[3]
    top.append((pred, iid))
    top.sort(key=lambda x: x[0], reverse=True)
    top = top[:10]

In [72]:
df2 = pd.read_csv('data/games.csv')
df2.head()

,app_id,title,date_release,win,mac,linux,rating,positive_ratio,user_reviews,price_final,price_original,discount,steam_deck
0,10090,Call of Duty: World at War,2008-11-18,True,False,False,Very Positive,92,37039,19.99,19.99,0.0,True
1,13500,Prince of Persia: Warrior Within™,2008-11-21,True,False,False,Very Positive,84,2199,9.99,9.99,0.0,True
2,22364,BRINK: Agents of Change,2011-08-03,True,False,False,Positive,85,21,2.99,2.99,0.0,True
3,113020,Monaco: What's Yours Is Mine,2013-04-24,True,True,True,Very Positive,92,3722,14.99,14.99,0.0,True
4,226560,Escape Dead Island,2014-11-18,True,False,False,Mixed,61,873,14.99,14.99,0.0,True

In [73]:
df2[df2['app_id'].isin([int(id) for r, id in top])]

,app_id,title,date_release,win,mac,linux,rating,positive_ratio,user_reviews,price_final,price_original,discount,steam_deck
2708,404040,Lords of Magic: Special Edition,2015-12-03,True,False,False,Very Positive,91,385,4.99,4.99,0.0,True
2985,1801650,Lost: Find,2021-12-03,True,False,False,Very Positive,88,1820,3.99,3.99,0.0,True
4326,758370,Through the Ages,2018-03-26,True,True,False,Very Positive,90,1686,15.99,15.99,0.0,True
6765,745880,Touhou Tenkuushou ~ Hidden Star in Four Seasons.,2017-11-17,True,False,False,Overwhelmingly Positive,98,4227,14.99,14.99,0.0,True
7013,1392650,BLASTRONAUT,2022-07-27,True,True,True,Very Positive,81,110,18.99,18.99,0.0,True
8691,851670,LUMINES REMASTERED,2018-06-26,True,False,False,Very Positive,95,398,14.99,14.99,0.0,True
9686,1718160,Crimzon Clover World EXplosion,2021-12-06,True,False,False,Very Positive,97,176,19.99,19.99,0.0,True
13001,1052990,A Monster's Expedition,2020-09-10,True,True,True,Overwhelmingly Positive,95,870,19.99,19.99,0.0,True
16287,373390,Contradiction: Spot The Liar,2015-07-10,True,True,False,Overwhelmingly Positive,95,2412,12.99,12.99,0.0,True
20673,1988540,The Zachtronics Solitaire Collection,2022-09-06,True,True,True,Very Positive,98,291,9.99,9.99,0.0,True

## Custom Algorithm on MovieLens